# Generated by Django 5.0.4 on 2025-04-25 12:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_remove_parkingrecord_entry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingrecord',
            name='entry_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
