# Generated by Django 5.0.4 on 2025-04-27 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_parkingrecord_entry_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('section', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='parkingrecord',
            name='section',
        ),
        migrations.AddField(
            model_name='parkingrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated parking fee', max_digits=8),
        ),
        migrations.AddField(
            model_name='parkingrecord',
            name='camera',
            field=models.ForeignKey(blank=True, help_text='Camera that logged this event', null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.camera'),
        ),
        migrations.AddField(
            model_name='parkingrecord',
            name='status',
            field=models.CharField(choices=[('PARKED', 'Parked'), ('EXITED', 'Exited'), ('FREE', 'Free')], default='FREE', max_length=10),
        ),
        migrations.AlterField(
            model_name='parkingrecord',
            name='slot',
            field=models.ForeignKey(blank=True, help_text='Assigned parking slot', null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.parkingslot'),
        ),
    ]
