# Generated by Django 5.0.4 on 2025-04-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_parkingslot_remove_parkingrecord_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingrecord',
            name='payment_link_id',
            field=models.CharField(blank=True, help_text='Razorpay Payment Link ID', max_length=100, null=True),
        ),
    ]
